services:
  talker:
    image: ghcr.io/bounverif/cyclonedds:latest 
    command: ddsperf pub size 16k -T KS
    network_mode: host
    
  listener:
    image: ghcr.io/bounverif/cyclonedds:latest 
    command: ddsperf sub -T KS
    network_mode: host
